In [1]:
import tensorflow as tf

2025-03-30 12:49:38.030975: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-30 12:49:38.039832: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1743349778.051143   19347 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743349778.054817   19347 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1743349778.063528   19347 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[-1, 3], [4, 2]])

W0000 00:00:1743349860.752201   19347 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [3]:
multiplicacao = tf.matmul(a, b)

In [4]:
print(a)
print('\n')
print(b)
print('\n')
print(multiplicacao)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[-1  3]
 [ 4  2]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[ 7  7]
 [13 17]], shape=(2, 2), dtype=int32)


In [6]:
multiplicacao2 = tf.matmul(b, a)
print(multiplicacao2)


tf.Tensor(
[[ 8 10]
 [10 16]], shape=(2, 2), dtype=int32)


In [7]:
a1 = tf.constant([[2, 3], [0, 1], [-1, 4]])
b1 = tf.constant([[1, 2, 3], [-2, 0, 4]])
multiplicacao3 = tf.matmul(a1, b1)

In [8]:
print(a1)
print('\n')
print(b1)
print('\n')
print(multiplicacao3)

tf.Tensor(
[[ 2  3]
 [ 0  1]
 [-1  4]], shape=(3, 2), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [-2  0  4]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]], shape=(3, 3), dtype=int32)
