In [2]:
import tensorflow as tf

In [7]:
a = tf.constant([[-1.0, 7.0, 5.0]], name = 'entradas')
b = tf.constant([[0.8, 0.1, 0]], name = 'pesos')

In [8]:
multiplicacao = tf.multiply(a, b)
soma = tf.reduce_sum(multiplicacao)

In [9]:
print(a)
print('\n')
print(b)
print('\n')
print(multiplicacao)
print('\n')
print(soma)

tf.Tensor([[-1.  7.  5.]], shape=(1, 3), dtype=float32)


tf.Tensor([[0.8 0.1 0. ]], shape=(1, 3), dtype=float32)


tf.Tensor([[-0.8  0.7  0. ]], shape=(1, 3), dtype=float32)


tf.Tensor(-0.100000024, shape=(), dtype=float32)
