In [3]:
import tensorflow as tf

In [4]:
a = tf.constant([9, 8, 7], name='a')
b = tf.constant([1, 2, 3], name='b')

W0000 00:00:1743349012.097766   17497 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [5]:
soma = a + b

In [6]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [7]:
print(a)

tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [8]:
print(soma)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [9]:
a1 = tf.constant([[1, 2, 3], [4, 5, 6]], name='a1')

In [10]:
type(a1)

tensorflow.python.framework.ops.EagerTensor

In [11]:
print(a1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
a1.shape

TensorShape([2, 3])

In [14]:
b1 = tf.constant([[1, 2, 3], [4, 5, 6]], name = 'b1')

In [17]:
soma1 = tf.add(a1, b1)

In [18]:
soma1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [19]:
print(a1)
print('\n')
print(b1)
print('\n')
print(soma1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [21]:
a2 = tf.constant([[1, 2, 3], [4, 5, 6]])
b2 = tf.constant([[1], [2]])
soma2 = tf.add(a2, b2)

In [22]:
print(a2)
print('\n')
print(b2)
print('\n')
print(soma2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)


tf.Tensor(
[[2 3 4]
 [6 7 8]], shape=(2, 3), dtype=int32)
