In [1]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
from sklearn.preprocessing import StandardScaler
scaler_X = StandardScaler()
X = scaler_X.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [4]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()
y.shape

(150,)

In [5]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [6]:
y = onehot.fit_transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.3, random_state=42)

In [8]:
X_treinamento.shape

(105, 4)

In [9]:
X_teste.shape

(45, 4)

In [10]:
import tensorflow as tf
import numpy as np

tf.random.set_seed(42)

tf.__version__


2025-04-27 15:40:26.948575: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-27 15:40:27.257526: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-27 15:40:27.319114: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-04-27 15:40:27.319130: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudar

'2.11.0'

In [11]:
neuronios_entrada = X.shape[1]
neuronios_entrada

4

In [12]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [13]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [14]:
W = {
    'oculta': tf.Variable(tf.random.normal([neuronios_entrada, neuronios_oculta])),
    'saida': tf.Variable(tf.random.normal([neuronios_oculta, neuronios_saida])),
}

2025-04-27 15:40:29.066259: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-27 15:40:29.073469: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-04-27 15:40:29.073538: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2025-04-27 15:40:29.073567: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2025-04-27 15:40:29.073592: W tensorflow/c

In [15]:
b = {
    'oculta': tf.Variable(tf.random.normal([neuronios_oculta])),
    'saida': tf.Variable(tf.random.normal([neuronios_saida])),
}

In [16]:
X_treinamento = tf.convert_to_tensor(X_treinamento, dtype=tf.float32, name='X')
y_treinamento = tf.convert_to_tensor(y_treinamento, dtype=tf.float32, name='y')
x_teste = tf.convert_to_tensor(X_teste, dtype=tf.float32, name='X')
y_teste = tf.convert_to_tensor(y_teste, dtype=tf.float32, name='y')

In [17]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

In [18]:
with tf.GradientTape() as tape:
    modelo = mlp(X_treinamento, W, b)
    erro = tf.reduce_mean(
        tf.nn.softmax_cross_entropy_with_logits(
            labels=y_treinamento,
            logits = modelo,
        )
    )

In [19]:
var_list = [W['oculta'], W['saida'], W['oculta'], b['saida']]

In [20]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.26454744],
       [-0.59722406, -1.9171132 , -0.62044144,  0.8504023 ]],
      dtype=float32)>

In [21]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.0001)
gradientes = tape.gradient(erro, var_list)
otimizador.apply_gradients(zip(gradientes, var_list))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

In [22]:
W['oculta']

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.32770288, -0.8423914 ,  0.31919935, -1.4073175 ],
       [-2.3878255 , -1.0390135 , -0.55755764,  0.5394727 ],
       [ 1.6991979 ,  0.28917092, -1.5063772 , -0.26431307],
       [-0.5969897 , -1.9168788 , -0.62020713,  0.8506366 ]],
      dtype=float32)>

In [23]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento))
dataset

<TensorSliceDataset element_spec=(TensorSpec(shape=(4,), dtype=tf.float32, name=None), TensorSpec(shape=(3,), dtype=tf.float32, name=None))>

In [24]:
batch_size = 8
dataset = dataset.batch(batch_size)
dataset

<BatchDataset element_spec=(TensorSpec(shape=(None, 4), dtype=tf.float32, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))>

In [25]:
next(iter(dataset))

(<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
 array([[-0.4160097 , -1.5131601 , -0.03296571, -0.26238683],
        [ 0.5533333 , -0.592373  ,  0.76275826,  0.3957741 ],
        [ 0.6745011 ,  0.09821729,  0.99010795,  0.79067063],
        [ 0.91683686, -0.13197948,  0.36489627,  0.26414192],
        [ 1.6438441 ,  1.249201  ,  1.3311325 ,  1.712096  ],
        [-0.17367394, -0.36217624,  0.25122142,  0.13250974],
        [ 2.1285155 , -0.13197948,  1.6153197 ,  1.1855673 ],
        [-0.29484183, -0.13197948,  0.4217337 ,  0.3957741 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(8, 3), dtype=float32, numpy=
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.]], dtype=float32)>)

In [26]:
dataset = tf.data.Dataset.from_tensor_slices((X_treinamento, y_treinamento)).batch(batch_size)

In [27]:
for epoca in range(3_000):
    for X_batch, y_batch in dataset:
        erro_medio = 0.0
        with tf.GradientTape() as tape:
            modelo = mlp(X_batch, W, b)
            erro = tf.reduce_mean(
                tf.nn.softmax_cross_entropy_with_logits(labels = y_batch, logits = modelo)
            )
        gradientes = tape.gradient(erro, var_list)
        otimizador.apply_gradients(zip(gradientes, var_list))
        erro_medio += erro.numpy()
    if epoca % 500 == 0:
        print(f'Época: {epoca + 1} erro: {erro_medio}')

Época: 1 erro: 0.671658992767334
Época: 501 erro: 0.035826168954372406
Época: 1001 erro: 0.013551034033298492
Época: 1501 erro: 0.008981424383819103
Época: 2001 erro: 0.0059393346309661865
Época: 2501 erro: 0.004178484436124563


In [28]:
W

{'oculta': <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.6227391 , -1.4035262 ,  0.8248544 , -1.3441819 ],
        [-2.2016382 ,  1.0123386 , -0.89177096,  0.46012095],
        [ 2.900441  , -2.4473748 , -1.112649  , -0.1988263 ],
        [ 1.3932617 , -4.6283937 , -1.1824287 ,  0.9144227 ]],
       dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[-2.3448014 , -0.64437693,  0.8989066 ],
        [ 1.3602599 , -1.3931427 , -1.2366922 ],
        [-1.4484204 ,  1.161869  , -1.4826738 ],
        [-1.3475906 , -1.6018872 , -0.56353754]], dtype=float32)>}

In [30]:
b

{'oculta': <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([-0.55909735, -0.5347214 ,  2.3730333 , -1.5725931 ], dtype=float32)>,
 'saida': <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-1.4626578 ,  0.58693427, -0.06116232], dtype=float32)>}

In [31]:
previsoes_teste = mlp(x_teste, W, b)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[-1.10175266e+01,  1.95618153e+00, -1.61749160e+00],
       [ 6.90886688e+00, -9.08236504e+00, -1.72086697e+01],
       [-2.78754463e+01, -4.38260984e+00,  7.07405281e+00],
       [-9.23400307e+00,  1.43910146e+00, -9.85356092e-01],
       [-1.39735117e+01,  1.65095496e+00, -1.14679408e+00],
       [ 5.17178011e+00, -7.46153736e+00, -1.70071030e+01],
       [-4.93313980e+00,  3.37082601e+00, -3.61371660e+00],
       [-1.25642681e+01, -1.24761796e+00,  2.60574651e+00],
       [-2.02773209e+01,  9.57650602e-01, -8.76224339e-02],
       [-9.17854691e+00,  3.10324764e+00, -3.16082597e+00],
       [-9.17801571e+00, -5.32508671e-01,  1.58908772e+00],
       [ 6.87852287e+00, -9.45123768e+00, -2.06630135e+01],
       [ 6.81183338e+00, -9.24813652e+00, -1.94288292e+01],
       [ 7.01913834e+00, -9.54104519e+00, -2.03189220e+01],
       [ 9.36065674e+00, -1.14412603e+01, -1.81130180e+01],
       [-5.05075598e+00,  1.33544064e+00, -9.517292

In [32]:
previsoes_teste = tf.nn.softmax(previsoes_teste)
previsoes_teste

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[2.25721988e-06, 9.72710729e-01, 2.72870846e-02],
       [9.99999821e-01, 1.13526205e-07, 3.35650188e-11],
       [6.63162423e-16, 1.05786394e-05, 9.99989331e-01],
       [2.12755931e-05, 9.18653905e-01, 8.13248754e-02],
       [1.54413925e-07, 9.42553937e-01, 5.74459285e-02],
       [9.99996722e-01, 3.26150712e-06, 2.33255665e-10],
       [2.47243122e-04, 9.98827755e-01, 9.25000990e-04],
       [2.52715608e-07, 2.07678080e-02, 9.79231954e-01],
       [4.43529019e-10, 7.39866197e-01, 2.60133833e-01],
       [4.62654180e-06, 9.98095393e-01, 1.89985102e-03],
       [1.88253180e-05, 1.07013412e-01, 8.92967761e-01],
       [9.99999821e-01, 8.09234919e-08, 1.09361045e-12],
       [9.99999821e-01, 1.05984704e-07, 4.01629251e-12],
       [9.99999821e-01, 6.42692441e-08, 1.34038993e-12],
       [9.99999940e-01, 9.24361310e-10, 1.17040080e-12],
       [1.52700616e-03, 9.06422615e-01, 9.20503587e-02],
       [5.59911184e-09, 9.66335705e-04,

In [33]:
previsoes_teste = tf.argmax(previsoes_teste, axis=1).numpy()
previsoes_teste

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [34]:
y_teste2 = tf.argmax(y_teste, axis=1).numpy()
y_teste2

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [35]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, previsoes_teste)
taxa_acerto

1.0