In [ ]:
import tensorflow as tf
import numpy as np

In [4]:
X = np.array(
    [
        [0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0],
        [1.0, 1.0],
    ]
)
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
y = np.array([
    [0.0],
    [0.0],
    [0.0],
    [1.0],
])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [17]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [8]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


In [9]:
def step(x):
    return tf.cast(tf.math.greater_equal(x, 1), tf.float64)

In [ ]:
epoca = 0
for i in range(15):
    epoca += 1

    # Foward pass
    camada_saida = tf.matmul(X, W)
    camada_saida_ativacao = step(camada_saida)

    # Backpropagation
    erro = tf.subtract(y, camada_saida_ativacao)
    delta = tf.matmul(X, erro, transpose_a=True)
    W.assign_add(tf.multiply(delta, 0.1))

    # Resumo da época
    erro_soma = tf.reduce_sum(erro).numpy()
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  1.0
Época: 6  Erro:  0.0


<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]])>

In [12]:
camada_saida_ativacao

NameError: name 'camada_saida_ativacao' is not defined