In [1]:
import tensorflow as tf
import numpy as np

2025-04-14 12:56:22.948759: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-14 12:56:23.362265: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-14 12:56:23.441915: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-04-14 12:56:23.441965: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudar

In [2]:
X = np.array(
    [
        [0.0, 0.0],
        [0.0, 1.0],
        [1.0, 0.0],
        [1.0, 1.0],
    ]
)
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
y = np.array([
    [0.0],
    [0.0],
    [0.0],
    [1.0],
])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [4]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

2025-04-14 12:56:26.018332: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-04-14 12:56:26.021699: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-04-14 12:56:26.021758: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2025-04-14 12:56:26.021785: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2025-04-14 12:56:26.021811: W tensorflow/c

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.],
       [0.]])>


In [6]:
def step(x):
    return tf.cast(tf.math.greater_equal(x, 1), tf.float64)

In [7]:
epoca = 0
for i in range(15):
    epoca += 1

    # Foward pass
    camada_saida = tf.matmul(X, W)
    camada_saida_ativacao = step(camada_saida)

    # Backpropagation
    erro = tf.subtract(y, camada_saida_ativacao)
    delta = tf.matmul(X, erro, transpose_a=True)
    W.assign_add(tf.multiply(delta, 0.1))

    # Resumo da época
    erro_soma = tf.reduce_sum(erro).numpy()
    print('Época:', epoca, ' Erro: ', erro_soma)
    if erro_soma == 0.0:
        break

Época: 1  Erro:  1.0
Época: 2  Erro:  1.0
Época: 3  Erro:  1.0
Época: 4  Erro:  1.0
Época: 5  Erro:  1.0
Época: 6  Erro:  0.0


In [13]:
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[0.5],
       [0.5]])>

In [10]:
camada_saida_teste = tf.matmul(X, W)
camada_saida_ativacao_teste = step(camada_saida_teste)
camada_saida_ativacao_teste.numpy()

array([[0.],
       [0.],
       [0.],
       [1.]])

In [12]:
tf.matmul(X, W)


<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0. ],
       [0.5],
       [0.5],
       [1. ]])>